[__config__]
oldver = "old.json"
newver = "new.json"
max_concurrency = 5

[minify]
source = "github"
github = "tdewolff/minify"
use_latest_release = true

[nvchecker]
source = "github"
github = "lilydjwg/nvchecker"
use_max_tag = true

[astroimagej]
source = "regex"
regex = "AstroImageJ_v(\\d+\\.\\d+\\.\\d+)(?:\\.00)?-linux-x86_64"
url = "http://www.astro.louisville.edu/software/astroimagej/installation_packages/"

[ttf-lxgw-wenkai-tc-mono]
source = "github"
github = "lxgw/LxgwWenkaiTC"
use_latest_release = true

[ttf-lxgw-bright-code-tc]
source = "github"
github = "lxgw/LxgwBright-Code"
use_latest_release = true

[xray]
source = "github"
github = "XTLS/Xray-core"
use_latest_release = true

[v2rayng]
source = "github"
github = "2dust/v2rayNG"
use_latest_release = true

[typst]
source = "github"
github = "typst/typst"
use_latest_release = true

[typst-cetz]
source = "github"
github = "cetz-package/cetz"
use_latest_release = true

[typst-physica]
source = "github"
github = "Leedehai/typst-physics"
use_latest_release = true

[typst-touying]
source = "github"
github = "touying-typ/touying"
use_latest_release = true

[typst-ctheorems]
source = "github"
github = "sahasatvik/typst-theorems"
use_latest_release = true

[typst-codly]
source = "github"
github = "Dherse/codly"
use_latest_release = true

[typst-modern-cv]
source = "github"
github = "DeveloperPaul123/modern-cv"
use_latest_release = true

[typst-codly-languages]
source = "htmlparser"
url = "https://typst.app/universe/package/codly-languages"
xpath = "/html/body/div/main/div[1]/div[2]/div/span"
